### ISSUE TITLE
Add raven.js to third-party alert service

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/third-party-library-alert#3]
Firefox Screenshots will be using Raven.js, shipping in desktop release 54.

**Comment by tomrittervg** [comment]
Sure!

So to see what version Firefox Screenshots is currently using, is this the line I should check: https://github.com/mozilla-services/screenshots/blob/e6c45b05536c60142fd965274edc0f934e40b8a0/package.json#L30 ?

And as far as where to file a bug, I presume https://github.com/mozilla-services/screenshots/issues is the right place?

**Comment by ckprice** [comment]
> So to see what version Firefox Screenshots is currently using, is this the line I should check: https://github.com/mozilla-services/screenshots/blob/e6c45b05536c60142fd965274edc0f934e40b8a0/package.json#L30 ?

Yep.

> And as far as where to file a bug, I presume https://github.com/mozilla-services/screenshots/issues is the right place?

What type of work is needed on our side? We opened this https://github.com/mozilla-services/screenshots/issues/2543 until I closed it with the assumption all the work was on this side. Feel free to re-open that one or start your own. Thanks.

**Comment by tomrittervg** [comment]
> What type of work is needed on our side? We opened this mozilla-services/screenshots#2543 until I closed it with the assumption all the work was on this side. Feel free to re-open that one or start your own. Thanks.

No I meant where should I file bugs when the library needs to be upgraded =) Those bugs look like this: https://bugzilla.mozilla.org/show_bug.cgi?id=1348788

**Comment by ckprice** [comment]
Ah, yeah https://github.com/mozilla-services/screenshots/issues is perfect, thank you.

**Comment by tomrittervg** [comment]
Oh, one more question (sorry) - what branch should I be looking at in the mozilla-services/screenshots project?

**Comment by ckprice** [comment]
master is good, thanks!
